schedule lazy dependencies
wooorm/linter-remark pull request #12
Opened 2018-01-19 23:48 UTC by BarryThePenguin

This isn't complete, but it's part way towards quicker load times when using `linter-remark`

I based this off the [`linter-eslint`](https://github.com/AtomLinter/linter-eslint/blob/081a492e02a4969f9033ce7eaa167c0ae8c1fd0b/src/main.js) package

The current changes reduced load time from >250ms to <5ms

There's most likely timing issues around the `engine` not being ready before `lint` is called

2018-01-20 00:17 UTC, Arcanemagus requested changes
Note that you also need to [cancel pending callbacks](https://github.com/AtomLinter/linter-eslint/blob/081a492e02a4969f9033ce7eaa167c0ae8c1fd0b/src/main.js#L240-L241) in `deactivate()`.

Also the point behind calling a `loadDeps` function in `linter-eslint` is that you then _also_ call that function before any of the dependencies are actually needed, so if the idle callback hasn't loaded them for you yet they are forced to load synchronously.

2018-01-20 01:26 UTC, BarryThePenguin commented
Thanks for the feedback ☺️ 

It now cancels the callbacks on `deactivate` and `loadDeps` is called just before the `engine` is built

2018-01-20 04:37 UTC, Arcanemagus approved these changes

2018-01-20 10:52 UTC, wooorm commented
Looks good!

2018-01-20 11:45 UTC, closed without merging

2018-01-20 11:45 UTC, wooorm commented
Done, albeit a little bit refactored!
I saw a note about not being ready yet, is that still the case, or is it good to go now?

2018-01-20 20:17 UTC, BarryThePenguin commented
Everything should be good now. @Arcanemagus covered everything I was originally missing

2018-01-20 20:31 UTC, Arcanemagus commented
FYI, this is an example of what this looks like in the CPU profiler:
![image](https://user-images.githubusercontent.com/427137/35187742-7c7a6c5a-fddd-11e7-8400-86dd3cb98f4e.png)

That's _why_ the "work" functions are given a name and not just fed in, since otherwise there is no way to know where they are coming from when profiling. This method has that `callback` function at the top of the stack instead of the named one directly on the top, but the benefit of abstracting that setup out outweighs that minor bit to me at least.

2018-01-21 09:52 UTC, wooorm commented
Published! Thanks both!